development:
  clients:
    default:
      database: raceday_development
      hosts:
        - localhost:27017
      options:

  options:

test:
  clients:
    default:
      database: raceday_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: mongodb://racer_db:sharovik86@ds159507.mlab.com:59507/heroku_r0xf1t9g
      options:
        connect_timeout: 15
