development:
  clients:
    default:
      database: raceday_development
      hosts:
        - localhost:27017
      options:

  options:

test:
  clients:
    default:
      database: raceday_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: mongodb://deploy:sharovik@ds159237.mlab.com:59237/racer_db
      options:
        connect_timeout: 15
